CameraExtrinsicMat:
   rows: 4
   cols: 4
   dt: d
   data: [ -0.003682, -0.999044, -0.043551, -0.045903,
     -0.048710,  0.043679, -0.997857, -0.595575,
     0.998806, -0.001553, -0.048824, -0.412103,
     0.000000,  0.000000,  0.000000,  1.000000]
CameraMat:
   rows: 3
   cols: 3
   dt: d
   data: [ 604.4962768554688, 0.0, 330.6304626464844,
           0.0, 604.25, 242.29705810546875,
           0.0, 0.0, 1.0]
DistCoeff:
   rows: 1
   cols: 5
   dt: d
   data: [ 0, 0, 0, 0, 0. ]
ImageSize: [ 640, 480 ]
ReprojectionError: 0
DistModel: plumb_bob
